/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function realname(): string
export function username(): string
export function lang(): string
export function devicename(): string
export function hostname(): string
export function distro(): string
export function desktopEnv(): string
export function machineid(): string
export function activeMacAddress(): string
export function macAddressByName(s: string): string
